### PR TITLE
Issue 6 - Resolve Show connected wallet info

### PR DESCRIPTION
**Pull request by danitome24**
## Description

This is a solution for issue #5 where I display some messages depending on wallet status.

Captura de pantalla de 2024-09-13 00-02-21
Captura de pantalla de 2024-09-13 00-03-24
Captura de pantalla de 2024-09-13 00-03-58

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #5_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: 0xaa4C60b784E2b3E485035399bF1b1aBDeD66A60f

### CODE REVIEW

**Comment by arjanjohan** [comment]
Nice texts in your implementation, but I would place it somewhere else. Now it can block content on the page. See screenshot:
image

Having it either in the header or in the wallet dropdown are both good solutions I think.

**Comment by danitome24** [comment]
good point @arjanjohan!! I will try to fix it. I did it to practice, so I'm just happy with feedback even if it don't get merged. :) Thanks for this comment.

**Comment by danitome24** [comment]
I just changed position of div from fixed to flex center on navbar. Now is blocking nothing.

Captura de Pantalla 2024-09-13 a las 16 26 26

**Comment by danitome24** [comment]
Closed by choosing another PR.

**Pull request closed without merging**
